docs: Updated the readme and change notes for upcoming release
redhat-developer/intellij-dependency-analytics pull request #149
Opened 2024-02-05 20:54 UTC by ritz303

Updated the `README.md` file, and the `change-notes` section in the `plugin.xml` file for an upcoming release.

2024-02-06 08:45 UTC, zvigrinberg requested changes

2024-02-06 08:45 UTC, zvigrinberg commented on src/main/resources/META-INF/plugin.xml
> +  <p>Python and Golang projects can only be analyzed with IntelliJ Ultimate Edition.</p>
@ritz303 It's true for golang project, as golang plugin ( used by the RHDA plugin)in intelli-J is only available for Ultimate Editon.
For Python, It's working with Community edition ( verified it).
![Peek 2024-02-06 10-43](https://github.com/redhat-developer/intellij-dependency-analytics/assets/75700623/89e0dbd1-f0c0-4428-baf4-6b3e0f1f94b4)

2024-02-06 23:07 UTC, ritz303 commented on src/main/resources/META-INF/plugin.xml
> +  <p>Python and Golang projects can only be analyzed with IntelliJ Ultimate Edition.</p>
Okay, thanks for the feedback!  I've updated the content accordingly.

2024-02-08 22:27 UTC, zvigrinberg approved these changes
lgtm

2024-03-02 21:13 UTC, merged